[2022-04-11 19:19:39,341] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_data.download_data_task manual__2022-04-11T19:19:37.050880+00:00 [queued]>
[2022-04-11 19:19:39,351] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_data.download_data_task manual__2022-04-11T19:19:37.050880+00:00 [queued]>
[2022-04-11 19:19:39,351] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 19:19:39,351] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-04-11 19:19:39,351] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 19:19:39,363] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): download_data_task> on 2022-04-11 19:19:37.050880+00:00
[2022-04-11 19:19:39,371] {standard_task_runner.py:52} INFO - Started process 353224 to run task
[2022-04-11 19:19:39,376] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'pbp_data', 'download_data_task', 'manual__2022-04-11T19:19:37.050880+00:00', '--job-id', '1718', '--raw', '--subdir', 'DAGS_FOLDER/nfl_to_gcs.py', '--cfg-path', '/tmp/tmpu_0_au9_', '--error-file', '/tmp/tmpdt7ab1ez']
[2022-04-11 19:19:39,378] {standard_task_runner.py:77} INFO - Job 1718: Subtask download_data_task
[2022-04-11 19:19:39,437] {logging_mixin.py:109} INFO - Running <TaskInstance: pbp_data.download_data_task manual__2022-04-11T19:19:37.050880+00:00 [running]> on host 4ed3eda454fd
[2022-04-11 19:19:39,498] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pbp_data
AIRFLOW_CTX_TASK_ID=download_data_task
AIRFLOW_CTX_EXECUTION_DATE=2022-04-11T19:19:37.050880+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-11T19:19:37.050880+00:00
[2022-04-11 19:19:39,504] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-11 19:19:39,505] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
[2022-04-11 19:19:39,506] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
[2022-04-11 19:19:39,507] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
[2022-04-11 19:19:39,508] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
[2022-04-11 19:19:39,509] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-04-11 19:19:39,510] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
[2022-04-11 19:19:39,510] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
[2022-04-11 19:19:39,511] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
[2022-04-11 19:19:39,512] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-04-11 19:19:39,513] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
[2022-04-11 19:19:39,513] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-04-11 19:19:39,514] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/nfl_to_gcs.py", line 35, in download_pbp_data
    pbp_data = pa.Table.from_pandas(nfl.load_pbp_data(year=season_year))
  File "/home/airflow/.local/lib/python3.7/site-packages/nflfastpy/__init__.py", line 28, in load_pbp_data
    raise SeasonNotFoundError('Play by play data is only available from 1999 to 2021')
nflfastpy.errors.SeasonNotFoundError: Play by play data is only available from 1999 to 2021
[2022-04-11 19:19:39,528] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=pbp_data, task_id=download_data_task, execution_date=20220411T191937, start_date=20220411T191939, end_date=20220411T191939
[2022-04-11 19:19:39,540] {standard_task_runner.py:92} ERROR - Failed to execute job 1718 for task download_data_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/nfl_to_gcs.py", line 35, in download_pbp_data
    pbp_data = pa.Table.from_pandas(nfl.load_pbp_data(year=season_year))
  File "/home/airflow/.local/lib/python3.7/site-packages/nflfastpy/__init__.py", line 28, in load_pbp_data
    raise SeasonNotFoundError('Play by play data is only available from 1999 to 2021')
nflfastpy.errors.SeasonNotFoundError: Play by play data is only available from 1999 to 2021
[2022-04-11 19:19:39,588] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-11 19:19:39,631] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
