[2022-04-24 14:45:53,997] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2000-01-01T00:00:00+00:00 [queued]>
[2022-04-24 14:45:54,014] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2000-01-01T00:00:00+00:00 [queued]>
[2022-04-24 14:45:54,015] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-24 14:45:54,015] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-04-24 14:45:54,015] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-24 14:45:54,036] {taskinstance.py:1259} INFO - Executing <Task(BigQueryInsertJobOperator): bq_ext_2_part_task> on 2000-01-01 00:00:00+00:00
[2022-04-24 14:45:54,045] {standard_task_runner.py:52} INFO - Started process 2761 to run task
[2022-04-24 14:45:54,058] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'pbp_data_bq_dag', 'bq_ext_2_part_task', 'scheduled__2000-01-01T00:00:00+00:00', '--job-id', '2165', '--raw', '--subdir', 'DAGS_FOLDER/nfl_gcs_to_bq.py', '--cfg-path', '/tmp/tmpl2noid58', '--error-file', '/tmp/tmpd5sqd6q_']
[2022-04-24 14:45:54,060] {standard_task_runner.py:77} INFO - Job 2165: Subtask bq_ext_2_part_task
[2022-04-24 14:45:54,156] {logging_mixin.py:109} INFO - Running <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2000-01-01T00:00:00+00:00 [running]> on host 28475d5c3e7a
[2022-04-24 14:45:54,254] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pbp_data_bq_dag
AIRFLOW_CTX_TASK_ID=bq_ext_2_part_task
AIRFLOW_CTX_EXECUTION_DATE=2000-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2000-01-01T00:00:00+00:00
[2022-04-24 14:45:54,256] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-24 14:45:54,266] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-24 14:45:54,278] {bigquery.py:1637} INFO - Inserting job ***_pbp_data_bq_dag_bq_ext_2_part_task_2000_01_01T00_00_00_00_00_ef5f51435e005aca551bef6c96291984
[2022-04-24 14:45:58,408] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=pbp_data_bq_dag, task_id=bq_ext_2_part_task, execution_date=20000101T000000, start_date=20220424T144553, end_date=20220424T144558
[2022-04-24 14:45:58,466] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-24 14:45:58,499] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-04-25 12:35:16,788] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2000-01-01T00:00:00+00:00 [queued]>
[2022-04-25 12:35:16,803] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2000-01-01T00:00:00+00:00 [queued]>
[2022-04-25 12:35:16,803] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 12:35:16,803] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-04-25 12:35:16,803] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 12:35:16,819] {taskinstance.py:1259} INFO - Executing <Task(BigQueryInsertJobOperator): bq_ext_2_part_task> on 2000-01-01 00:00:00+00:00
[2022-04-25 12:35:16,829] {standard_task_runner.py:52} INFO - Started process 508 to run task
[2022-04-25 12:35:16,839] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'pbp_data_bq_dag', 'bq_ext_2_part_task', 'scheduled__2000-01-01T00:00:00+00:00', '--job-id', '2327', '--raw', '--subdir', 'DAGS_FOLDER/nfl_gcs_to_bq.py', '--cfg-path', '/tmp/tmp87_icote', '--error-file', '/tmp/tmpnupzngeg']
[2022-04-25 12:35:16,840] {standard_task_runner.py:77} INFO - Job 2327: Subtask bq_ext_2_part_task
[2022-04-25 12:35:16,899] {logging_mixin.py:109} INFO - Running <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2000-01-01T00:00:00+00:00 [running]> on host de169a1be7ed
[2022-04-25 12:35:16,956] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pbp_data_bq_dag
AIRFLOW_CTX_TASK_ID=bq_ext_2_part_task
AIRFLOW_CTX_EXECUTION_DATE=2000-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2000-01-01T00:00:00+00:00
[2022-04-25 12:35:16,958] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-25 12:35:16,965] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-25 12:35:16,972] {bigquery.py:1637} INFO - Inserting job ***_pbp_data_bq_dag_bq_ext_2_part_task_2000_01_01T00_00_00_00_00_00f2178e7e03af68b4be751029869bc0
[2022-04-25 12:35:21,098] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=pbp_data_bq_dag, task_id=bq_ext_2_part_task, execution_date=20000101T000000, start_date=20220425T123516, end_date=20220425T123521
[2022-04-25 12:35:21,149] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-25 12:35:21,179] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-04-25 12:42:16,432] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2000-01-01T00:00:00+00:00 [queued]>
[2022-04-25 12:42:16,461] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2000-01-01T00:00:00+00:00 [queued]>
[2022-04-25 12:42:16,461] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 12:42:16,461] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-04-25 12:42:16,461] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 12:42:16,479] {taskinstance.py:1259} INFO - Executing <Task(BigQueryInsertJobOperator): bq_ext_2_part_task> on 2000-01-01 00:00:00+00:00
[2022-04-25 12:42:16,488] {standard_task_runner.py:52} INFO - Started process 1473 to run task
[2022-04-25 12:42:16,500] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'pbp_data_bq_dag', 'bq_ext_2_part_task', 'scheduled__2000-01-01T00:00:00+00:00', '--job-id', '2372', '--raw', '--subdir', 'DAGS_FOLDER/nfl_gcs_to_bq.py', '--cfg-path', '/tmp/tmp7eiujfky', '--error-file', '/tmp/tmp9juabt8n']
[2022-04-25 12:42:16,501] {standard_task_runner.py:77} INFO - Job 2372: Subtask bq_ext_2_part_task
[2022-04-25 12:42:16,580] {logging_mixin.py:109} INFO - Running <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2000-01-01T00:00:00+00:00 [running]> on host de169a1be7ed
[2022-04-25 12:42:16,662] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pbp_data_bq_dag
AIRFLOW_CTX_TASK_ID=bq_ext_2_part_task
AIRFLOW_CTX_EXECUTION_DATE=2000-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2000-01-01T00:00:00+00:00
[2022-04-25 12:42:16,664] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-25 12:42:16,675] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-25 12:42:16,687] {bigquery.py:1637} INFO - Inserting job ***_pbp_data_bq_dag_bq_ext_2_part_task_2000_01_01T00_00_00_00_00_08812466b79864d380d32640b4bbca86
[2022-04-25 12:42:20,793] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=pbp_data_bq_dag, task_id=bq_ext_2_part_task, execution_date=20000101T000000, start_date=20220425T124216, end_date=20220425T124220
[2022-04-25 12:42:20,851] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-25 12:42:20,883] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-04-25 12:43:53,086] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2000-01-01T00:00:00+00:00 [queued]>
[2022-04-25 12:43:53,115] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2000-01-01T00:00:00+00:00 [queued]>
[2022-04-25 12:43:53,116] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 12:43:53,116] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-04-25 12:43:53,116] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 12:43:53,150] {taskinstance.py:1259} INFO - Executing <Task(BigQueryInsertJobOperator): bq_ext_2_part_task> on 2000-01-01 00:00:00+00:00
[2022-04-25 12:43:53,158] {standard_task_runner.py:52} INFO - Started process 1757 to run task
[2022-04-25 12:43:53,170] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'pbp_data_bq_dag', 'bq_ext_2_part_task', 'scheduled__2000-01-01T00:00:00+00:00', '--job-id', '2392', '--raw', '--subdir', 'DAGS_FOLDER/nfl_gcs_to_bq.py', '--cfg-path', '/tmp/tmp06aw7q7j', '--error-file', '/tmp/tmp62an74u2']
[2022-04-25 12:43:53,172] {standard_task_runner.py:77} INFO - Job 2392: Subtask bq_ext_2_part_task
[2022-04-25 12:43:53,372] {logging_mixin.py:109} INFO - Running <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2000-01-01T00:00:00+00:00 [running]> on host de169a1be7ed
[2022-04-25 12:43:53,483] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pbp_data_bq_dag
AIRFLOW_CTX_TASK_ID=bq_ext_2_part_task
AIRFLOW_CTX_EXECUTION_DATE=2000-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2000-01-01T00:00:00+00:00
[2022-04-25 12:43:53,485] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-25 12:43:53,507] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-25 12:43:53,531] {bigquery.py:1637} INFO - Inserting job ***_pbp_data_bq_dag_bq_ext_2_part_task_2000_01_01T00_00_00_00_00_03a592801c1d0894c50fc3aca7cd28f4
[2022-04-25 12:43:54,401] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2287, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2253, in _submit_job
    job_id=job_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1639, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1447, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1437, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 727, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading table: nfl_project.external_pbp_data, error message: Parquet column 'assist_tackle_3_team' has type DOUBLE which does not match the target cpp_type STRING_PIECE.

(job ID: airflow_pbp_data_bq_dag_bq_ext_2_part_task_2000_01_01T00_00_00_00_00_03a592801c1d0894c50fc3aca7cd28f4)

                                                                                                                -----Query Job SQL Follows-----                                                                                                                

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:CREATE OR REPLACE TABLE nfl_project.pbp_data_partitioned                     PARTITION BY DATE(game_timestamp) AS                     SELECT *, PARSE_TIMESTAMP('%F', game_date) AS game_timestamp                     FROM nfl_project.external_pbp_data;
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
[2022-04-25 12:43:54,432] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=pbp_data_bq_dag, task_id=bq_ext_2_part_task, execution_date=20000101T000000, start_date=20220425T124353, end_date=20220425T124354
[2022-04-25 12:43:54,475] {standard_task_runner.py:92} ERROR - Failed to execute job 2392 for task bq_ext_2_part_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2287, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2253, in _submit_job
    job_id=job_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1639, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1447, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1437, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 727, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading table: nfl_project.external_pbp_data, error message: Parquet column 'assist_tackle_3_team' has type DOUBLE which does not match the target cpp_type STRING_PIECE.

(job ID: airflow_pbp_data_bq_dag_bq_ext_2_part_task_2000_01_01T00_00_00_00_00_03a592801c1d0894c50fc3aca7cd28f4)

                                                                                                                -----Query Job SQL Follows-----                                                                                                                

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:CREATE OR REPLACE TABLE nfl_project.pbp_data_partitioned                     PARTITION BY DATE(game_timestamp) AS                     SELECT *, PARSE_TIMESTAMP('%F', game_date) AS game_timestamp                     FROM nfl_project.external_pbp_data;
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
[2022-04-25 12:43:54,528] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-25 12:43:54,581] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-04-25 12:58:15,067] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2000-01-01T00:00:00+00:00 [queued]>
[2022-04-25 12:58:15,077] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2000-01-01T00:00:00+00:00 [queued]>
[2022-04-25 12:58:15,077] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 12:58:15,078] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-04-25 12:58:15,078] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 12:58:15,090] {taskinstance.py:1259} INFO - Executing <Task(BigQueryInsertJobOperator): bq_ext_2_part_task> on 2000-01-01 00:00:00+00:00
[2022-04-25 12:58:15,095] {standard_task_runner.py:52} INFO - Started process 3360 to run task
[2022-04-25 12:58:15,101] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'pbp_data_bq_dag', 'bq_ext_2_part_task', 'scheduled__2000-01-01T00:00:00+00:00', '--job-id', '2417', '--raw', '--subdir', 'DAGS_FOLDER/nfl_gcs_to_bq.py', '--cfg-path', '/tmp/tmphybh6tra', '--error-file', '/tmp/tmphuo23f5d']
[2022-04-25 12:58:15,102] {standard_task_runner.py:77} INFO - Job 2417: Subtask bq_ext_2_part_task
[2022-04-25 12:58:15,171] {logging_mixin.py:109} INFO - Running <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2000-01-01T00:00:00+00:00 [running]> on host de169a1be7ed
[2022-04-25 12:58:15,231] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pbp_data_bq_dag
AIRFLOW_CTX_TASK_ID=bq_ext_2_part_task
AIRFLOW_CTX_EXECUTION_DATE=2000-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2000-01-01T00:00:00+00:00
[2022-04-25 12:58:15,233] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-25 12:58:15,242] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-25 12:58:15,254] {bigquery.py:1637} INFO - Inserting job ***_pbp_data_bq_dag_bq_ext_2_part_task_2000_01_01T00_00_00_00_00_64ccd11fe4cbdb758f35ea8edce8a957
[2022-04-25 12:58:16,115] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2287, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2253, in _submit_job
    job_id=job_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1639, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1447, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1437, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 727, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading table: nfl_project.external_pbp_data, error message: Parquet column 'assist_tackle_4_player_id' has type DOUBLE which does not match the target cpp_type STRING_PIECE.

(job ID: airflow_pbp_data_bq_dag_bq_ext_2_part_task_2000_01_01T00_00_00_00_00_64ccd11fe4cbdb758f35ea8edce8a957)

                                                                                                                -----Query Job SQL Follows-----                                                                                                                

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:CREATE OR REPLACE TABLE nfl_project.pbp_data_partitioned                     PARTITION BY DATE(game_timestamp) AS                     SELECT *, PARSE_TIMESTAMP('%F', game_date) AS game_timestamp                     FROM nfl_project.external_pbp_data;
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
[2022-04-25 12:58:16,131] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=pbp_data_bq_dag, task_id=bq_ext_2_part_task, execution_date=20000101T000000, start_date=20220425T125815, end_date=20220425T125816
[2022-04-25 12:58:16,154] {standard_task_runner.py:92} ERROR - Failed to execute job 2417 for task bq_ext_2_part_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2287, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2253, in _submit_job
    job_id=job_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1639, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1447, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1437, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 727, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading table: nfl_project.external_pbp_data, error message: Parquet column 'assist_tackle_4_player_id' has type DOUBLE which does not match the target cpp_type STRING_PIECE.

(job ID: airflow_pbp_data_bq_dag_bq_ext_2_part_task_2000_01_01T00_00_00_00_00_64ccd11fe4cbdb758f35ea8edce8a957)

                                                                                                                -----Query Job SQL Follows-----                                                                                                                

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:CREATE OR REPLACE TABLE nfl_project.pbp_data_partitioned                     PARTITION BY DATE(game_timestamp) AS                     SELECT *, PARSE_TIMESTAMP('%F', game_date) AS game_timestamp                     FROM nfl_project.external_pbp_data;
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
[2022-04-25 12:58:16,171] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-25 12:58:16,226] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
