[2022-04-11 20:00:05,090] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: injury_data.download_data_task scheduled__2008-01-01T00:00:00+00:00 [queued]>
[2022-04-11 20:00:05,119] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: injury_data.download_data_task scheduled__2008-01-01T00:00:00+00:00 [queued]>
[2022-04-11 20:00:05,119] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 20:00:05,119] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-04-11 20:00:05,119] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 20:00:05,156] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): download_data_task> on 2008-01-01 00:00:00+00:00
[2022-04-11 20:00:05,167] {standard_task_runner.py:52} INFO - Started process 356822 to run task
[2022-04-11 20:00:05,180] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'injury_data', 'download_data_task', 'scheduled__2008-01-01T00:00:00+00:00', '--job-id', '1756', '--raw', '--subdir', 'DAGS_FOLDER/nfl_to_gcs.py', '--cfg-path', '/tmp/tmpmy2z3jah', '--error-file', '/tmp/tmpb9eqbp2b']
[2022-04-11 20:00:05,181] {standard_task_runner.py:77} INFO - Job 1756: Subtask download_data_task
[2022-04-11 20:00:05,315] {logging_mixin.py:109} INFO - Running <TaskInstance: injury_data.download_data_task scheduled__2008-01-01T00:00:00+00:00 [running]> on host 4ed3eda454fd
[2022-04-11 20:00:05,460] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=injury_data
AIRFLOW_CTX_TASK_ID=download_data_task
AIRFLOW_CTX_EXECUTION_DATE=2008-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2008-01-01T00:00:00+00:00
[2022-04-11 20:00:05,471] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-11 20:00:05,473] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
[2022-04-11 20:00:05,475] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
[2022-04-11 20:00:05,488] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
[2022-04-11 20:00:05,490] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
[2022-04-11 20:00:05,491] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-04-11 20:00:05,492] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
[2022-04-11 20:00:05,495] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
[2022-04-11 20:00:05,496] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
[2022-04-11 20:00:05,497] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-04-11 20:00:05,498] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
[2022-04-11 20:00:05,499] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-04-11 20:00:05,500] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/nfl_to_gcs.py", line 40, in download_injury_data
    injury_data = pa.Table.from_pandas(nfl.load_injury_data(year=season_year))
  File "/home/airflow/.local/lib/python3.7/site-packages/nflfastpy/__init__.py", line 70, in load_injury_data
    raise SeasonNotFoundError('Injury data is only available from 2009 to 2021')
nflfastpy.errors.SeasonNotFoundError: Injury data is only available from 2009 to 2021
[2022-04-11 20:00:05,530] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=injury_data, task_id=download_data_task, execution_date=20080101T000000, start_date=20220411T200005, end_date=20220411T200005
[2022-04-11 20:00:05,551] {standard_task_runner.py:92} ERROR - Failed to execute job 1756 for task download_data_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/nfl_to_gcs.py", line 40, in download_injury_data
    injury_data = pa.Table.from_pandas(nfl.load_injury_data(year=season_year))
  File "/home/airflow/.local/lib/python3.7/site-packages/nflfastpy/__init__.py", line 70, in load_injury_data
    raise SeasonNotFoundError('Injury data is only available from 2009 to 2021')
nflfastpy.errors.SeasonNotFoundError: Injury data is only available from 2009 to 2021
[2022-04-11 20:00:05,584] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-11 20:00:05,652] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
